%\VignetteIndexEntry{Bioconductor LaTeX Style}
%\VignettePackage{BiocStyle}
%\VignetteEngine{knitr::knitr}

\documentclass{beamer}

\usetheme{Boadilla}
\setbeamertemplate{footline}
{
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right,rightskip=1em]{section in head/foot}%
    \usebeamerfont{subsection in head/foot}\hspace*{2ex}\insertshorttitle
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.4\paperwidth,ht=2.25ex,dp=1ex,left,leftskip=1em]{subsection in head/foot}%
    \usebeamerfont{section in head/foot}\insertsectionhead\hspace*{2ex}
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.1\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} / \inserttotalframenumber\hspace*{2ex}
  \end{beamercolorbox}}%
  \vskip0pt%
}

\newcommand{\software}[1]{\textsl{#1}}
\newcommand\R{\software{R}}
%
\newcommand\Bioconductor{\software{Bioconductor}}
\newcommand{\Rpackage}[1]{\textsl{#1}}
\newcommand\Biocpkg[1]{%
  {\href{http://bioconductor.org/packages/#1}%
    {\Rpackage{#1}}}}
\newcommand\CRANpkg[1]{
  {\href{http://cran.r-project.org/package=#1}%
    {\Rpackage{#1}}}}
\newcommand{\Rcode}[1]{\texttt{#1}}

\title{Classic, rich, tidy}
\author{Martin Morgan}
\institute[RPCI]{
  Roswell Park Cancer Institute\\
  Buffalo, NY, USA\\
  \href{mailto:martin.morgan@roswellpark.org}{martin.morgan@roswellpark.org}}
\date{13 December 2016}

\begin{document}

\maketitle

\begin{frame}{Classic, tidy, rich: RNA-seq count data}
  Classic
  \begin{itemize}
  \item Sample x (phenotype + expression) Feature \Rcode{data.frame}
  \end{itemize}
  Tidy
  \begin{itemize}
  \item 'Melt' expression values to two long columns, replicated
    phenotype columns. End result: long data frame.
  \end{itemize}
  Rich, e.g., \Rcode{SummarizedExperiment}
  \begin{itemize}
  \item Phenotype and expression data manipulated in a coordinated
    fashion but stored separately.
  \end{itemize}
\end{frame}

\begin{frame}[fragile]{Classic, tidy, rich: RNA-seq count data}
  \begin{semiverbatim}
m0 <- colMeans(classic[, -(1:22)])
m1 <- tidy %>% group_by(probeset) %>%
    summarize(mean=mean(exprs))
m2 <- rowMeans(assay(rich))

df0 <- data.frame(mean=m0)
df1 <- m1
df2 <- data.frame(mean=m2)

ggplot(df1, aes(mean)) + geom_density()
  \end{semiverbatim}
\end{frame}

\begin{frame}{Classic, tidy, rich: RNA-seq count data}
  \begin{columns}[t]
    \column{.5\textwidth}
    Vocabulary
    \begin{itemize}
    \item Classic: extensive
    \item Tidy: restricted ‘endomorphisms’
    \item Rich: extensive, ‘meaningful’
    \end{itemize}
    Constraints (e.g., probes \& samples)
    \begin{itemize}
    \item Tidy: implicit
    \item Classic, Rich: explicit
    \end{itemize}
    Flexibility
    \begin{itemize}
    \item Classic, tidy: general-purpose
    \item Rich: specialized
    \end{itemize}

    \column{.5\textwidth}
    Programming contract
    \begin{itemize}
    \item   Classic, tidy: limited
    \item Rich: strict
    \end{itemize}
    Lessons learned / best practices
    \begin{itemize}
    \item Considerable value in semantically rich structures
    \item Current implementations trade-off user and developer
      convenience
    \item Endomorphism, simple vocabulary, consistent paradigm aid use
    \end{itemize}
  \end{columns}
\end{frame}

\begin{frame}{Complexity in \Biocpkg{GenomicRanges} (examples)}
  \begin{itemize}
  \item Constructor / show method: need to know \Rcode{factor-Rle},
    \Rcode{IRanges} as well as \Rcode{GRanges}
  \item \Rcode{findOverlaps} could be endomorphic, e.g., returning
    intersection of ranges with \Rcode{query}, \Rcode{subject} reverse
    map as metadata columns.
  \item \Rcode{show} 'chunk-wise wrapping' versus \CRANpkg{dplyr}
    displaying extra column names; long column data types.
  \end{itemize}
\end{frame}

\end{document}
