%\VignetteIndexEntry{Bioconductor LaTeX Style}
%\VignettePackage{BiocStyle}
%\VignetteEngine{knitr::knitr}

\documentclass{beamer}

\usetheme{Boadilla}
\setbeamertemplate{footline}
{
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right,rightskip=1em]{section in head/foot}%
    \usebeamerfont{subsection in head/foot}\hspace*{2ex}\insertshorttitle
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.4\paperwidth,ht=2.25ex,dp=1ex,left,leftskip=1em]{subsection in head/foot}%
    \usebeamerfont{section in head/foot}\insertsectionhead\hspace*{2ex}
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.1\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} / \inserttotalframenumber\hspace*{2ex}
  \end{beamercolorbox}}%
  \vskip0pt%
}

\newcommand{\software}[1]{\textsl{#1}}
\newcommand\R{\software{R}}
%
\newcommand\Bioconductor{\software{Bioconductor}}
\newcommand{\Rpackage}[1]{\textsl{#1}}
\newcommand\Biocpkg[1]{%
  {\href{http://bioconductor.org/packages/#1}%
    {\Rpackage{#1}}}}
\newcommand\CRANpkg[1]{
  {\href{http://cran.r-project.org/package=#1}%
    {\Rpackage{#1}}}}
\newcommand{\Rcode}[1]{\texttt{#1}}

\title{The \Bioconductor{} Project: Current Status}
\author{Martin Morgan}
\institute[RPCI]{
  Roswell Park Cancer Institute\\
  Buffalo, NY, USA\\
  \href{mailto:martin.morgan@roswellpark.org}{martin.morgan@roswellpark.org}}
\date{5 December, 2017}

\begin{document}

\maketitle

\section{Introduction}

\begin{frame}{\Bioconductor{}}
  \begin{columns}
  \column{.5\textwidth}
  \includegraphics[width=.8\textwidth]{bioconductor_logo_rgb.pdf}
  \bigskip\par
  \includegraphics[width=.15\textwidth]{Rlogo.png}
  \hspace{1em}
  \includegraphics[width=.3\textwidth]{nid61380-a1-rpci-cmyk-black.pdf}
  \column{.5\textwidth}
  Analysis and comprehension of high-throughput genomic data.
  \begin{itemize}
  \item Started 2002
  \item 14736 \R{} packages -- developed by `us' and user-contributed.
  \end{itemize}
  Well-used and respected.
  \begin{itemize}
  \item 53k unique IP downloads / month.
  \item 21,700 PubMedCentral citations.
  \end{itemize}
  More than 1000 maintainers!
  \end{columns}
\end{frame}

\section{State of the project}

\begin{frame}{State of the project}
  \begin{columns}
    \column{.5\textwidth}
    \only<1>{
      \includegraphics[width=\textwidth]{packages-per-release.pdf}
    }
    \only<2>{
      \includegraphics[width=\textwidth]{web-visits.png}
      \bigskip\par\centering
      \includegraphics[width=.8\textwidth]{web-users-country.png}
    }
    \only<3>{
      \href{https://bioconductor.org}{https://bioconductor.org}\par
      \href{https://support.bioconductor.org}{https://support.bioconductor.org}
    }
    \only<4>{
      \includegraphics[width=\textwidth]{contributions.png}
    }
    \only<5>{
      \begin{center}
      \includegraphics[width=!, height=2em]{logo_nhgri.png}
      \bigskip\par
      \includegraphics[width=.8\textwidth]{nci-logo-full.png}
      \bigskip\par
      \includegraphics[width=.6\textwidth]{sound_wordmark.png}
      \end{center}
    }
    \column{.5\textwidth}
    \begin{itemize}
    \item Packages
    \item Users
    \item Web \& support sites
    \item Training, workflows, \& meetings
    \item New package submission
    \item Release \& devel builders
    \item Funding
    \item Governance: (annual) Scientific Advisory Board; (monthly)
      Technical Advisory Board
    \end{itemize}
  \end{columns}
\end{frame}

\section{Recent developments}

%% \begin{frame}[fragile]{Recent developments}
%%   \begin{itemize}
%%   \item Git!
%% \begin{semiverbatim}
%%   git clone https://git.bioconductor.org/packages/limma
%%   git clone git@git.bioconductor.org:packages/DESeq2
%% \end{semiverbatim}
%%   \item Large Single Cell
%%     \begin{itemize}
%%     \item \Biocpkg{SingleCellExperiment}
%%     \item \Biocpkg{HDF5Array}
%%     \end{itemize}
%%   \item Lessons from 100's of package reviews
%%   \end{itemize}
%% \end{frame}

%% \begin{frame}[fragile]{Large single-cell data}
%%   \begin{semiverbatim}
%% > sce = TENxBrainData::TENxBrainData()
%% snapshotDate(): 2017-10-30
%% > sce
%% class: SingleCellExperiment 
%% dim: 27998 1306127 
%% metadata(0):
%% assays(1): counts
%% rownames: NULL
%% rowData names(2): Ensembl Symbol
%% colnames(1306127): AAACCTGAGATAGGAG-1 AAACCTGAGCGGCTTC-1 ...
%%   TTTGTCAGTTAAAGTG-133 TTTGTCATCTGAAAGA-133
%% colData names(4): Barcode Sequence Library Mouse
%% reducedDimNames(0):
%% spikeNames(0):
%%   \end{semiverbatim}
%% \end{frame}

%% \begin{frame}{Large single-cell data}
%%   \begin{itemize}
%%   \item Chunk-wise iteration (often transparent to the user /
%%     developer).
%%   \item Marginal summaries in \Rcode{rowData}, \Rcode{colData}.
%%   \item Supporting infrastructure: \Biocpkg{ExperimentHub},
%%     \Biocpkg{rhdf5}, \Biocpkg{HDF5Array},
%%     \Biocpkg{DelayedMatrixStats}, \Biocpkg{beachmat}.
%%   \end{itemize}
%% \end{frame}

\section{Lessons learned}

\begin{frame}[fragile]{Why use or contribute to \Bioconductor?}
  \begin{columns}
    \column{.35\textwidth} 
    \begin{itemize}
    \item Recognition.
    \item Access \& permanance.
    \item Interoperability.
    \item Documentation.
    \item Support.
    \item Tested.
    \end{itemize}
    \column{.65\textwidth}
    \only<1>{
      \includegraphics[width=.9\textwidth]{bioconductor_logo_rgb.pdf}
    }
    \only<2>{
      \includegraphics[]{in_bioc.png}
    }
    \only<3>{
\begin{semiverbatim}
git\$ grep -l SummarizedExperiment \\\par
\enskip\enskip */DESCRIPTION | wc -l\par
165
\end{semiverbatim}
    }
    \only<4>{
      \includegraphics[width=.9\textwidth]{documentation.png}
    }
    \only<5>{
      \includegraphics[width=.9\textwidth]{support.png}
    }
    \only<6>{
      \includegraphics[width=.9\textwidth]{build.png}
    }
  \end{columns}
\end{frame}

\begin{frame}{Our contributors}
  \begin{columns}
    \column{.5\textwidth}
    \includegraphics[width=\textwidth]{packages-per-developer}
    \column{.5\textwidth}
    \begin{itemize}
    \item 1060 unique maintainers.
    \item 791 'first time' authors.
    \end{itemize}
  \end{columns}
\end{frame}

\begin{frame}[allowframebreaks]{Lessons learned from package reviews}
  \begin{enumerate}
  \item Interoperability
    \begin{itemize}
    \item Use feature $\times$ sample \Rcode{SummarizedExperiment}, not
      sample $\times$ feature matrix.
    \item Use paradigms familiar to \Bioconductor{} users.
    \end{itemize}
  \item Reuse
    \begin{itemize}
    \item Use \Rcode{rtracklayer::import.bed()}, not custom parser.
    \end{itemize}
  \item Robust code
    \begin{itemize}
    \item Edge cases: \Rcode{seq\_len()} / \Rcode{seq\_along()}, not
      \Rcode{1:n}.
    \item Code complexity: \Rcode{vapply()}, not \Rcode{sapply()}.
    \end{itemize}
  \item Performant code
    \begin{itemize}
    \item \emph{Vectorize} rather than \emph{iterate} (\Rcode{for},
      \Rcode{lapply()}, \Rcode{apply()} are all iterative).
    \item Reuse (e.g., \CRANpkg{matrixStats}) before C / C++ implementation.
    \end{itemize}
    \framebreak
  \item Tested code
    \begin{itemize}
    \item Essential: evaluated example and vignette code chunks.
    \item Desireable: unit tests, e.g., \Biocpkg{testthat}.
    \end{itemize}
  \item Time and space limits.
    \begin{itemize}
    \item Excessive computation may represent inefficient code.
    \item Challenging to identify rich but modest data for
      illustration.
    \item Experiment data packages, work flows, F1000 papers as venues
      for more expensive / comprehensive reproducible analysis.
    \end{itemize}
  \item Ambition
    \begin{itemize}
    \item Implement essential features well.
    \item Avoid dependencies on packages for marginal value.
    \end{itemize}
  \item Pretty
    \begin{itemize}
    \item 'Poetry' with short lines, consistent and ample spacing,
      standard formatting.
    \end{itemize}
  \end{enumerate}
\end{frame}

\section{Future challenges}

\begin{frame}{Future challenges}
  \begin{itemize}
  \item Large data.
  \item Cloud. Possible visions:
    \begin{itemize}
    \item As now, but `in the cloud' -- \url{https://rstudio.cloud}.
    \item Integrated with `third party' compute efforts, e.g., NCI,
      NIH in the United States.
    \item Pay-as-you-play -- use existing \Bioconductor{} AMIs or
      docker containers.
    \end{itemize}
  \end{itemize}
\end{frame}

\section{Acknowledgments}

\begin{frame}{Acknowledgments}
  Core team: Qian Liu, Valerie Obenchain, Herv\'e Pag\`es, Marcel
  Ramos, Lori Shepherd, Nitesh Turaga, Daniel van Twisk.
  \medskip\par
  Technical advisory board: Vincent Carey, Kasper Hansen, Wolfgang
  Huber, Robert Gentleman, Rafael Irizzary, Levi Waldron, Michael
  Lawrence, Sean Davis, Aedin Culhane
  \medskip\par Scientific advisory board: Vincent Carey (Brigham \&
  Women's), Wolfgang Huber (EBI), Rafael Irizzary (Dana Farber), Jan
  Vitek (Northeastern University), Robert Gentleman (23andMe).
  \medskip\par
  Research reported in this presentation was supported by the National
  Human Genome Research Institute and the National Cancer Institute of
  the National Institutes of Health under award numbers U41HG004059
  and U24CA180996. The content is solely the responsibility of the
  authors and does not necessarily represent the official views of the
  National Institutes of Health.
\end{frame}

\end{document}
